"""Disaster-stop characterization for MEANREV_FADE_2M. NO tuning — observe only.

The fade engine has no stop (exit is reversion-only). Its ENTER/EXIT signal stream
is therefore independent of any stop, so we generate the canonical stopless trade
list ONCE (same bars, same harness path as the verified PF~5.06 run), then OVERLAY
a disaster stop per trade: if any bar's low between entry and the signal-exit bar
pierces entry - STOP_ATR*ATR_at_entry, the trade closes early at the stop instead.
This never adds/removes entries or modifies the engine — it only truncates losers.

ATR_at_entry comes from a parallel _Atr (the engine's exact indicator code, fed the
same bars) so it equals the ATR the entry decision used. Stop fills are assumed to
execute exactly at the stop price (optimistic — real fills slip worse).

Run: .venv/bin/python research/disaster_stop_sweep.py
"""
import os
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.backtest.drift_control import load_bars
from src.engine.meanrev_fade import MeanRevFadeEngine, MeanRevConfig
from src.engine.v4 import _Atr

DATA = "src/data/MNQ_2m_12mo_databento.csv"
FRICTION = 1.0            # pts; matches the harness / verified run
POINT_VALUE = 2.0         # MNQ $/pt (prop $ convention)
SPLIT = date(2025, 12, 15)  # blind = entries strictly before this (earliest ~6mo)
STOP_VALUES = [1.5, 2.0, 2.5, 3.0, 4.0, None]
OUT = "research/disaster_stop_sweep.md"


def canonical_trades(bars):
    """The verified stopless trade stream: list of dicts with entry/signal-exit
    indices, prices, entry ATR, entry ts. Reproduces run_backtest's trades."""
    cfg = MeanRevConfig()
    engine = MeanRevFadeEngine(cfg)
    atrt = _Atr(cfg.atr_len)
    trades, cur = [], None
    for i, b in enumerate(bars):
        atr = atrt.update(b.high, b.low, b.close)        # == engine's internal atr
        dec = engine.on_bar(b.open, b.high, b.low, b.close)
        if dec is None:
            continue
        s = str(dec["signal"])
        if s.endswith("ENTER_LONG"):
            cur = {"entry_idx": i, "entry_px": dec["price"], "entry_atr": atr, "entry_ts": b.ts}
        elif s.endswith("EXIT_LONG") and cur is not None:
            cur["sig_exit_idx"] = i; cur["sig_exit_px"] = dec["price"]; cur["exit_ts"] = b.ts
            trades.append(cur); cur = None
    return trades


def realize(t, bars, stop_atr):
    """(pnl_pts, reason) for one trade under a given STOP_ATR (None = no stop)."""
    if stop_atr is not None:
        stop = t["entry_px"] - stop_atr * t["entry_atr"]
        for k in range(t["entry_idx"] + 1, t["sig_exit_idx"] + 1):
            if bars[k].low <= stop:                       # intrabar stop fires first
                return (stop - t["entry_px"] - FRICTION, "stop")
    return (t["sig_exit_px"] - t["entry_px"] - FRICTION, "signal")


def metrics(realized):
    """realized: list of (pnl, reason), in chronological (entry) order."""
    pnls = [p for p, _ in realized]
    n = len(pnls)
    if n == 0:
        return dict(n=0, win=0.0, net=0.0, pf=float("nan"), mdd=0.0,
                    stopped=0, signal=0)
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p <= 0]
    loss_sum = sum(losses)
    pf = (sum(wins) / abs(loss_sum)) if loss_sum != 0 else float("inf")
    cum = peak = mdd = 0.0
    for p in pnls:
        cum += p; peak = max(peak, cum); mdd = min(mdd, cum - peak)
    stopped = sum(1 for _, r in realized if r == "stop")
    return dict(n=n, win=len(wins) / n * 100, net=sum(pnls), pf=pf, mdd=mdd,
                stopped=stopped, signal=n - stopped)


def _pf(v):
    return "∞" if v == float("inf") else (f"{v:.2f}" if v == v else "—")


def row(label, m):
    return (f"| {label} | {m['n']} | {m['win']:.0f}% | {m['net']:+.0f} | "
            f"{_pf(m['pf'])} | {m['mdd']:.0f} | ${m['mdd']*POINT_VALUE:,.0f} | "
            f"{m['stopped']} | {m['signal']} |")


def table(title, trades, bars):
    lines = [f"### {title}", "",
             "| STOP_ATR | trades | win% | net pts | PF | maxDD pts | maxDD $ | stopped | signal-exit |",
             "|---|---|---|---|---|---|---|---|---|"]
    for sv in STOP_VALUES:
        realized = [realize(t, bars, sv) for t in trades]
        label = "none (verified)" if sv is None else f"{sv:.1f}"
        lines.append(row(label, metrics(realized)))
    return "\n".join(lines)


def main():
    bars = load_bars(DATA)
    canon = canonical_trades(bars)
    blind = [t for t in canon if t["entry_ts"].date() < SPLIT]
    span = f"{bars[0].ts.date()} .. {bars[-1].ts.date()}"

    md = [
        "# Disaster-stop sweep — MEANREV_FADE_2M",
        "",
        f"**Dataset:** `{DATA}` ({len(bars):,} 2-min bars, {span}) · "
        f"**friction:** {FRICTION} pt · **$ conv:** MNQ ${POINT_VALUE:.0f}/pt · "
        f"**generated by** `research/disaster_stop_sweep.py`",
        "",
        "Characterization only — engine unchanged, no tuning. The stop is overlaid on "
        "the verified stopless signal stream (it changes loser exits, not entries). "
        "`none` reproduces the verified run as the baseline. Stop fills assumed exactly "
        "at the stop price (optimistic vs real slippage).",
        "",
        table("Full 12-month", canon, bars),
        "",
        table(f"Blind earliest-6mo (entries before {SPLIT})", blind, bars),
        "",
        "_Columns: stopped = trades closed by the disaster stop; signal-exit = trades "
        "that reached the engine's reversion exit. maxDD on cumulative net pts, "
        "trade-ordered._",
        "",
    ]
    out = "\n".join(md) + "\n"
    with open(OUT, "w") as f:
        f.write(out)
    print(out)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
